#!/usr/bin/env bash
set -euo pipefail
trap 'printf "{\"hookSpecificOutput\":{\"message\":\"⚠️ pr-traceability: hook error — check jq/input format\"}}" ; exit 0' ERR

# PostToolUse hook (matcher: Bash)
# After `gh pr create` runs, appends spec traceability block to the PR description
# and updates SPEC.md Implementations section with the PR URL.
# Reads session context from ~/.claude/.silver-bullet/spec-session (written at session start).

# Security: restrict file creation permissions (user-only)
umask 0077

# Source symlink-write guard (SEC-02)
_lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/lib" && pwd 2>/dev/null)" || _lib_dir=""
if [[ -n "$_lib_dir" && -f "$_lib_dir/nofollow-guard.sh" ]]; then
  # shellcheck source=lib/nofollow-guard.sh
  source "$_lib_dir/nofollow-guard.sh"
else
  sb_guard_nofollow() { [[ -L "$1" ]] && { printf 'ERROR: refusing to write through symlink: %s\n' "$1" >&2; exit 1; }; return 0; }
  sb_safe_write()    { [[ -L "$1" ]] && rm -f -- "$1"; return 0; }
fi

# jq is required for JSON parsing
if ! command -v jq >/dev/null 2>&1; then
  printf '{"hookSpecificOutput":{"message":"⚠️ Silver Bullet hooks require jq. Install: brew install jq (macOS) / apt install jq (Linux)"}}'
  exit 0
fi

# Resolve gh CLI at runtime (CR-01 fix: cross-platform)
GH_BIN=$(command -v gh || command -v /opt/homebrew/bin/gh || command -v /usr/local/bin/gh || true)
if [[ -z "$GH_BIN" ]]; then
  printf '{"hookSpecificOutput":{"message":"⚠️ pr-traceability: gh CLI not found — traceability block skipped."}}'
  exit 0
fi

# Read JSON from stdin
input=$(cat)

# Extract command from Bash tool input
cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // ""')

# Only trigger on actual `gh pr create` commands
if ! printf '%s' "$cmd" | grep -qE '\bgh pr create\b'; then
  exit 0
fi

# Read spec-session file — if missing, no spec session, exit silently
SB_STATE_DIR="${HOME}/.claude/.silver-bullet"
spec_session_file="${SB_STATE_DIR}/spec-session"

if [[ ! -f "$spec_session_file" ]]; then
  exit 0
fi

# Extract spec-version and jira-id with validation (CR-03 fix)
spec_version=$(grep '^spec-version=' "$spec_session_file" | cut -d'=' -f2 | grep -E '^[0-9]+(\.[0-9]+)*$' || echo "unknown")
jira_id=$(grep '^jira-id=' "$spec_session_file" | cut -d'=' -f2 | grep -E '^[A-Z]+-[0-9]+$' || echo "")

# Read WARN findings from VALIDATION.md if it exists
warn_items=""
if [[ -f ".planning/VALIDATION.md" ]]; then
  warn_items=$(grep 'FINDING \[WARN\]' .planning/VALIDATION.md || true)
fi

# Get the current PR URL (just created by the gh pr create command)
pr_url=$("$GH_BIN" pr view --json url --jq '.url' 2>/dev/null || true)

if [[ -z "$pr_url" ]]; then
  printf '{"hookSpecificOutput":{"message":"⚠️ pr-traceability: Could not determine PR URL — traceability block skipped."}}'
  exit 0
fi

# Read existing PR body — do NOT overwrite (Pitfall 4: append only)
existing_body=$("$GH_BIN" pr view --json body --jq '.body' 2>/dev/null || true)

# Build traceability block via jq (SEC-03) — safe JSON/body construction.
# Strip backticks (break out of fenced code block) and HTML-escape <, >, &
# before passing to jq, so raw HTML cannot render in GitHub's PR description.
safe_warn=$(printf '%s' "${warn_items:-None}" \
  | tr -d '`' \
  | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')

new_body=$(jq -n -r \
  --arg existing "$existing_body" \
  --arg v "$spec_version" \
  --arg j "${jira_id:-n/a}" \
  --arg warn "$safe_warn" \
  '$existing + "\n---\n## Spec Traceability (auto-generated by Silver Bullet)\n- Spec: .planning/SPEC.md (v" + $v + ")\n- JIRA: " + $j + "\n- Requirements covered: see SPEC.md ## Acceptance Criteria\n\n### Deferred items (WARN findings from silver-validate)\n```\n" + $warn + "\n```\n"')

# Write to temp file and update PR (M10: trap ensures cleanup on signal)
tmpfile=$(mktemp)
trap 'rm -f -- "$tmpfile"' EXIT INT TERM
printf '%s' "$new_body" > "$tmpfile"
"$GH_BIN" pr edit "$pr_url" --body-file "$tmpfile" 2>/dev/null || true
rm -f -- "$tmpfile"
trap - EXIT INT TERM  # disarm all handlers — file already removed on success path

# TRAC-04: Update SPEC.md Implementations section with PR URL
SPEC=".planning/SPEC.md"
if [[ -f "$SPEC" ]]; then
  today=$(date '+%Y-%m-%d')
  entry="- PR: ${pr_url} | Date: ${today} | Spec-version: ${spec_version}"

  # Insert entry after the <!-- Populated automatically comment (idempotent — skip if already inserted)
  if ! grep -qF "$pr_url" "$SPEC" 2>/dev/null; then
    ENTRY="$entry" awk 'BEGIN{e=ENVIRON["ENTRY"]} /<!-- Populated automatically/ { print; print e; next } { print }' "$SPEC" > "${SPEC}.tmp" && mv "${SPEC}.tmp" "$SPEC"

    git add "$SPEC" 2>/dev/null || true
    # SPEC.md staged for commit — auto-commit removed (HI-03: hooks should not commit)
  fi
fi

msg=$(printf 'Spec traceability added to PR description.' | jq -Rs '.')
printf '{"hookSpecificOutput":{"message":%s}}' "$msg"

exit 0
